---
abstract: 'CPAN authors who are Debian Developers'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  Acme::CPANAuthors: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-CPANAuthors-DebianDev
requires:
  Acme::CPANAuthors::Register: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Acme-CPANAuthors-DebianDev
  repository: http://github.com/book/Acme-CPANAuthors-DebianDev.git
version: '1.000'
